print("Hello World")
print("What is your name?")
myname = input()
print("it is good to meet you, " + myname)
print("the length of your name is: ")
print(len(myname))
print("What is your age ?")
myage = input()
print("you will be " + str(int(myage) + 1) + " in a year")
